---
title: "gmcsDataPrep"
author: ""
date: "21 January 2019"
output: pdf_document
---

# Overview

This module uses climate data and permanent sampling plot data to prepare a multivariate mixed effect model of growth, mortality, and net biomass change. The PSP data is supplied by the module PSP_clean. The PSP_clean data includes BC, Alberta, Saskatchewan, and the first NFI PSP measurement, which is mainly western Canada. However, because the module requires repeat measurements, this module should only be used with a studyAreaLarge that covers at a minimum part of BC, Alberta, or Saskatchewan. 

The module does not estimate unobserved growth and mortality (trees that grew and died between census measurements). The formulas are included as comments. It is not advisable to estimate the unobserved mortality and growth of species, and although the multivariate model does not have a species term, we intended for the model to one day include species. Consequently, we exclude unobserved mortality and growth (estimates are usually 0.5-1.5% of total growth and mortality, so no biggie). 


## R Markdown

R Markdown syntax allows R code, outputs, and figures to be rendered in the documentation.

For help writing in R Markdown, see http://rmarkdown.rstudio.com/.

# Usage

```{r module_usage}
library(SpaDES)
library(LandR)
library(sf)
library(fasterize)
library(raster)

setPaths(modulePath = file.path("../"))
getPaths() # shows where the 4 relevant paths are

times <- list(start = 2011, end = 2012)

#the study area isn't necessary to test models - it is only used to satisfy climate data prep. Smaller is better
studyArea <- randomStudyArea(size=  10000*6.25*400)
templateRaster <- raster(extent(studyArea), crs = crs(studyArea), res = c(500,500))
templateRaster <- setValues(templateRaster, 1)

#this is the continugous ecoregions of the RIA. It is suggested that users pass a studyAreaPSP 
#it should represent a geographic area where trees would be expected to have a similar climate response
studyAreaPSP <- prepInputs(url = 'https://drive.google.com/open?id=10yhleaumhwa3hAv_8o7TE15lyesgkDV_',
                                 destinationPath = tempdir())

parameters <- list(
  gmcsDataPrep = list(
    "minDBH" = 9, #the minimum DBH varies over time and space, so 9+ is recommended
    "useHeight" = TRUE,
    ".useCache" = FALSE,
    "PSPdataTypes" = "all",
    "PSPab_damageColsToExclude" = NULL,
    "PSPbc_damageColsToExclude" = NULL,
    "PSPnfi_damageColsToExclude" = NULL,
    "PSPperiod" = c(1958,2019),
    #an alternative mortality model - gamma not possible due to 0 
    "mortalityModel" = quote(glmmPQL(mortality ~ logAge*(ATA + CMI) + logAge^2 *(ATA + CMI) + ATA*CMI, random = ~1 | OrigPlotID1,
                                    weights = scale(PSPmodelData$plotSize^0.5 * PSPmodelData$periodLength, center = FALSE),
                                    data = PSPmodelData, family = "gaussian"(link = 'identity'))),
    #the 'new' growth model with quadratic. 
    "growthModel" = quote(glmmPQL(growth ~ logAge*(ATA + CMI) + logAge^2 * (CMI + ATA) + ATA:CMI, random = ~1 | OrigPlotID1,
                                    weights = scale(PSPmodelData$plotSize^0.5 * PSPmodelData$periodLength, center = FALSE),
                                    data = PSPmodelData, family = 'Gamma'(link = 'log'))),
    #the original model with quadratic term
    # "growthModel" = quote(nlme::lme(growth ~ logAge*(ATA + CMI) + logAge^2 *(ATA + CMI) + ATA*CMI, random = ~1 | OrigPlotID1,
    #                                 weights = varFunc(~plotSize^0.5 * periodLength), data = PSPmodelData)),
    #Yong's original growth model
    # "growthModel" = quote(nlme::lme(growth ~ logAge*(ATA + CMI) + ATA*CMI, random = ~1 | OrigPlotID1,
    #                                  weights = varFunc(~plotSize^0.5 * periodLength), data = PSPmodelData)),
    "PSPvalidationPeriod" = NULL #pass NULL to instead randomly sample the validation data
  )
)


modules <- list("gmcsDataPrep")
objects <- list(studyArea = studyArea, 
                rasterToMatch = templateRaster,
                studyAreaPSP = studyAreaPSP)
inputs <- list()
outputs <- list()

mySim <- simInit(times = times, params = parameters, modules = modules,
                 objects = objects)

mySimOut <- spades(mySim)

```




# Events

Describe what happens for each event type.

## Plotting

Write what is plotted.

## Saving

Write what is saved.

# Data dependencies

## Input data

How to obtain input data, and a description of the data required by the module.
If `sourceURL` is specified, `downloadData("gmcsDataPrep", "path/to/modules/dir")` may be sufficient.

## Output data

Description of the module outputs.

# Links to other modules

Describe any anticipated linkages to other modules.

